<h2>
    <?php echo $this->translate('Generete fake datas') ?>
    <?php echo ' ' . $count . ' count ' ?>
    <?php echo ' ' . $this->translate("sucessfull") ?>
</h2>
<a href="<?php echo $this->url('admin/lucene', ['action' => 'index']);?>">
    &raquo; <?php echo $this->translate('Lucene') ?>
</a>
<br>
<a href="<?php echo $this->url('admin/user-manager', ['action' => 'index']);?>">
    &raquo; <?php echo $this->translate('User manager') ?>
</a>