<h1><?php echo $this->translate('Generete fake datas') ?></h1>
<a href="<?php echo $this->url('admin/lucene', ['action' => 'index']);?>">
    &raquo; <?php echo $this->translate('Lucene') ?>
</a>
<br>
<br>
<?php
echo $this->form()->openTag($form);
foreach ($form as $element) {
    echo '<div class="mb-3 row">';
    echo '    <label class="col-sm-2 col-form-label">'.$this->formLabel($element).'</label>';
    echo '    <div class="col-sm-10">';
    echo $this->formElement($element);
    echo '    </div>';
    echo '    <div>'.$this->formElementErrors($element).'</div>';
    echo '</div>';
}
echo $this->form()->closeTag();
?>