<h3><?php echo $this->translate('Books') ?></h3>

<?php
echo $this->form()->openTag($form);
foreach ($form as $element) {
    echo '<div class="mb-3 row">';
    echo '    <label class="col-sm-2 col-form-label">'.$this->formLabel($element).'</label>';
    echo '    <div class="col-sm-10">';
    echo $this->formElement($element);
    echo '    </div>';
    echo '    <div>'.$this->formElementErrors($element).'</div>';
    echo '</div>';
}
echo $this->form()->closeTag();
?>

<table class="table">
<tr>
    <th style="width: 300px"><?php echo $this->translate('authors') ?></th>
    <th><?php echo $this->translate('title') ?></th>
    <th><?php echo $this->translate('image') ?></th>
    <th><?php echo $this->translate('url') ?></th>
</tr>
<?php foreach ($books as $book) : ?>
<tr>
    <td>
        <?php echo $this->escapeHtml(implode(
            ',',
            $book['volumeInfo']['authors'] ? $book['volumeInfo']['authors'] : []
        ));?>
    </td>
    <td>
        <?php echo $this->escapeHtml($book['volumeInfo']['title']);?>
    </td>
    <td>
        <img src="<?php echo $this->escapeHtml($book['volumeInfo']['imageLinks']['thumbnail'])?>" height="100px"
             alt="<?php echo $this->escapeHtml($book['volumeInfo']['title']);?>"/>
    </td>
    <td>
        <a href="<?php echo $this->escapeHtml($book['selfLink']);?>" target="_blank">
            <?php echo $this->translate('json') ?>
        </a>
    </td>
</tr>
<?php endforeach; ?>
</table>