<a href="<?php echo $this->url('admin/store-admin');?>">
    <?php echo $this->translate('View Products') ?>
</a> |
<a href="<?php echo $this->url('admin/store-admin', ['action' => 'listOrders']);?>">
    <?php echo $this->translate('View Orders') ?>
</a>
<hr />
<h3><?php echo $this->translate('Store Orders') ?></h3>
<table class="table">
<tr>
    <th><?php echo $this->translate('ID') ?></th>
    <th><?php echo $this->translate('Date') ?></th>
    <th><?php echo $this->translate('Total') ?></th>
    <th><?php echo $this->translate('Status') ?></th>
    <th><?php echo $this->translate('Actions') ?></th>
</tr>
<?php foreach ($storeOrders as $order) : ?>
<tr>
    <td><?php echo $this->escapeHtml($order->id);?></td>
    <td><?php echo $this->escapeHtml($order->stamp);?></td>
    <td><?php echo $this->escapeHtml($order->total);?></td>
    <td><?php echo $this->escapeHtml($order->status);?></td>
    <td>
        <a href="<?php echo $this->url('admin/store-admin', ['action' => 'viewOrder', 'id' => $order->id]);?>">
            <?php echo $this->translate('View Order') ?>
        </a>
    </td>
</tr>
<?php endforeach; ?>
</table>
