<h3>My Uploads</h3>
<br>
<a href="<?php echo $this->url(
    'admin/upload-manager',
    ['action' => 'upload']
);?>">&raquo; Add Upload</a>
<table class="table">
<tr>
    <th>Label</th>
    <th>Filename</th>
    <th>Actions</th>
</tr>
<?php foreach ($myUploads as $upload) : ?>
<tr>
    <td><?php echo $this->escapeHtml($upload->label);?></td>
    <td><?php echo $this->escapeHtml($upload->filename);?></td>
    <td>
        <a href="<?php echo $this->url('admin/upload-manager', ['action' => 'edit', 'id' => $upload->id]);?>">
            Edit</a> |
        <a href="<?php echo $this->url('admin/upload-manager', ['action' => 'delete', 'id' => $upload->id]);?>"
           onclick="return confirm('Are you sure?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<br>
<br>
<h3>Shared Uploads</h3>
<br>
<table class="table">
<tr>
    <th>Label</th>
    <th>Filename</th>
    <th>Shared By</th>
</tr>
<?php foreach ($sharedUploadsList as $uploadId => $upload) : ?>
<tr>
    <td><?php echo $this->escapeHtml($upload['label']);?></td>
    <td><a href="<?php echo $this->escapeHtml($this->url(
        'admin/upload-manager',
        ['action' => 'fileDownload', 'id' => $uploadId]
    ));?>">Download</a> </td>
    <td><?php echo $this->escapeHtml($upload['owner']);?></td>
</tr>
<?php endforeach; ?>
</table>
<hr />