<section class="contact-us">
<h2><?php echo $this->translate('HTML5 Form') ?></h2>

<?php if ($this->error) : ?>
<p class="error">
    <?php echo $this->translate('There were one or more isues with your submission. Please correct them as indicated below.') ?>
</p>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(null, ['controller' => 'Html5', 'action' => 'multiUpload']));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>
<dl class="zend_form">
<dt><?php echo $this->translate('Multi Upload Form') ?></dt>

<dt><?php echo $this->formLabel($form->get('imageupload')); ?></dt>
<dd><?php
    echo $this->formFile($form->get('imageupload'));
    echo $this->formElementErrors($form->get('imageupload'));
?></dd>

<dd><?php echo $this->formSubmit($form->get('submit'));?></dd>

</dl>
<?php echo $this->form()->closeTag() ?>
</section>
