
<section class="upload">
<h2>Upload</h2>

<?php if ($this->error) : ?>
<p class="error">
    There were one or more isues with your submission. Please correct them as 
    indicated below.
</p>
<?php endif ?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(null, ['controller' => 'MediaManager', 'action' => 'processUpload']));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>
<table>
    <tr>
        <td> <?php echo $this->formLabel($form->get('label')); ?>
        </td>
        <td> <?php
        echo $this->formElement($form->get('label'));
        echo $this->formElementErrors($form->get('label'));
        ?>
        </td>
        
    </tr>
    <tr>
        <td> <?php echo $this->formLabel($form->get('imageupload')); ?>
        </td>
        <td> <?php
        echo $this->formElement($form->get('imageupload'));
        echo $this->formElementErrors($form->get('imageupload'));
        ?>
        </td>
        
    </tr>
    <tr>
        <td> <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
        </td>
        <td> &nbsp;
        </td>
        
    </tr>
</table>

<?php echo $this->form()->closeTag() ?>
</section>
